### ISSUE TITLE
iOS 15.1

### ISSUE THREAD

**Issue by sterrana** [cordova-sms/cordova-sms-plugin#223]
Hello,
I've just updated my iPhone to iOS 5.1 and the app totally crash when the send() method is performed.

Error:
"This application is modifying the autolayout engine from a background thread, which can lead to engine corruption and weird crashes. This will cause an exception in a future release."

Any solution for this?

Thanx.

**Comment by sterrana** [comment]
Resolved. For some reason the plugin wasn't updated to the last version in the iOS platform.

**Comment by Gurpreet68** [comment]
Can you please explain how you fixed this?  Currently my app is using the 1.0.1 version which is the latest one but still crashing.
Please help me how you update to the last version in IOS?
